// Generated by https://quicktype.io

export interface InterfaceInfoUsuarioSica3 {
    user_info:     UserInfo;
    empleado_info: EmpleadoInfo;
}

export interface EmpleadoInfo {
    id:                 number;
    matricula:          string;
    madre:              string;
    hora_entrada:       string;
    hora_salida:        string;
    pago_riesgo:        string;
    cedula_profesional: null;
    checa:              string;
    cuenta_bancaria:    null;
    activo:             number;
    fecha_alta:         string;
    fecha_base:         string;
    fecha_baja:         string;
    observaciones:      string;
    motivo_baja:        null;
    medico:             null;
    guardias:           string[];
    nombramiento:       string;
    atencion_medica:    string;
    numero_afiliacion:  null;
    foto:               null;
    id_persona:         number;
    id_tipoempleado:    number;
    id_plaza:           number;
    id_pension:         number;
    id_tiporecurso:     number;
    id_puesto:          number;
    id_departamento:    number;
    id_turno:           number;
    id_categoria:       number;
    id_sindicato:       number;
    id_banco:           null;
    id_financiamiento:  number;
    id_motivo_baja:     number;
    idUser:             null;
    created_at:         string;
    updated_at:         string;
    deleted_at:         null;
}

export interface UserInfo {
    id:               number;
    name:             string;
    username:         string;
    email:            string;
    created_at:       string;
    updated_at:       string;
    deleted_at:       null;
    id_tipopersona:   number;
    id_persona:       number;
    id_empleado:      number;
    nombre_completo:  string;
    tipo_persona:     string;
    persona:          Persona;
    cat_tipo_persona: CatTipoPersona;
}

export interface CatTipoPersona {
    id:         number;
    modelo:     string;
    nombre:     string;
    inactivo:   number;
    created_at: string;
    updated_at: string;
    deleted_at: null;
}

export interface Persona {
    id:                       number;
    primer_apellido:          string;
    segundo_apellido:         string;
    nombres:                  string;
    fecha_nacimiento:         string;
    curp:                     string;
    rfc:                      string;
    sexo:                     string;
    estado_nacimiento:        string;
    medios_comunicacion:      MediosComunicacion[];
    fecha_defuncion:          null;
    defuncion_observaciones:  null;
    id_ocupacion:             number;
    id_estadocivil:           number;
    id_tiposangre:            number;
    id_escolaridad:           number;
    id_religion:              number;
    id_nacionalidad:          number;
    curp_verificada:          string;
    motivo_verificacion_curp: null;
    created_user:             string;
    created_at:               string;
    updated_at:               string;
    deleted_at:               null;
}

export interface MediosComunicacion {
    tipo:        string;
    descripcion: null | string;
}